export const SOCKET_INIT_MESSAGES = 'SOCKET_INIT_MESSAGES';
export const SOCKET_GET_CHATS = 'SOCKET_GET_CHATS';
export const SOCKET_NEW_CHAT = 'SOCKET_NEW_CHAT';
export const SOCKET_EXISTING_CHAT = 'SOCKET_EXISTING_CHAT';
export const SOCKET_NEW_MESSAGE = 'SOCKET_NEW_MESSAGE';
export const SOCKET_USER_TYPING = 'SOCKET_USER_TYPING';

export const SET_CHATS = 'SET_CHATS';
export const GET_CHATS = 'GET_CHATS';
export const IS_CHATS_LOADING = 'IS_CHATS_LOADING';
export const GET_CURRENT_CHAT = 'GET_CURRENT_CHAT';
export const SET_IS_SENDING = 'SET_IS_SENDING';
export const GET_IS_SENDING = 'GET_IS_SENDING';

export const INIT_CHAT = 'INIT_CHAT';
export const CHAT_MESSAGE = 'CHAT_MESSAGE';
export const ADD_NEW_CHAT = 'ADD_NEW_CHAT';
export const SET_CHAT_MESSAGES = 'SET_CHAT_MESSAGES';
export const INSERT_NEW_MESSAGE = 'INSERT_NEW_MESSAGE';
export const CONNECT_TO_CHAT = 'CONNECT_TO_CHAT';
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export const USER_TYPING = 'USER_TYPING';
