export const SET_ALL_USERS = 'SET_ALL_USERS';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const UPDATE_USER_ONLINE = 'UPDATE_USER_ONLINE';
export const GET_USER_BY_NAME = 'GET_USER_BY_NAME';
export const IS_USER_LOADING = 'IS_USER_LOADING';

export const SOCKET_USER_UPDATE_ONLINE = 'SOCKET_USER_UPDATE_ONLINE';
export const SOCKET_ALL_USERS = 'SOCKET_ALL_USERS';
